#!/usr/bin/env python3
"""Generate one per-index job resource from each _pipelines/pipeline_configs/<name>.yml config.

Adding an Elasticsearch index to the framework is: add _pipelines/pipeline_configs/<name>.yml (and its
_pipelines/pipeline_views/<view_name>.sql), then rerun this generator. It writes resources/<name>.job.yml,
one per config, all pointing at the shared notebook notebooks/run_index_pipeline.py.

Usage:
  python scripts/gen_jobs.py            # (re)generate resources/<name>.job.yml files
  python scripts/gen_jobs.py --check    # exit non-zero if any generated file is missing/stale/orphaned

--check is the drift guard: run it in CI (or before deploy) so a config edit that was not
regenerated - or a generated job left behind by a deleted/renamed config - fails loudly instead of
deploying a stale job set.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys

import yaml

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Import the shared config schema from the repo root, so validation is not re-implemented here.
sys.path.insert(0, _REPO_ROOT)
from pipeline_lib.config import (  # noqa: E402
    PipelineConfigError,
    _require_identifier,
    job_base_parameters,
    job_parameters,
    load_config,
)

_CONFIG_DIR = os.path.join(_REPO_ROOT, "_pipelines", "pipeline_configs")
_RESOURCES_DIR = os.path.join(_REPO_ROOT, "resources")
# Reusable job-cluster specs referenced by a config's compute.job_cluster_config key (see load_job_cluster_spec).
_JOB_CLUSTER_CONFIG_DIR = os.path.join(_REPO_ROOT, "_pipelines", "job_cluster_configs")
# Bundle root; the Elasticsearch host configs are declared here (see load_es_host_configs).
_DATABRICKS_YML = os.path.join(_REPO_ROOT, "databricks.yml")

# The three fields every Elasticsearch host config carries. A host config is declared in databricks.yml
# as a `type: complex` variable whose default mapping has exactly these keys (see the variables block there).
_ES_HOST_CONFIG_FIELDS = frozenset({"es_host_url", "secret_scope_name", "secret_key_name"})

# The field a cluster config carries. Like a host config, a cluster config is a `type: complex` variable
# whose default mapping has exactly this key: an existing_cluster pipeline names one via
# compute.cluster_config, and the generator emits existing_cluster_id: ${var.<name>.cluster_id}.
_CLUSTER_CONFIG_FIELDS = frozenset({"cluster_id"})

# Config files may use either extension; both are treated identically.
_CONFIG_GLOBS = ("*.yml", "*.yaml")

# A config's stem becomes the Databricks bundle resource key `index_pipeline_<stem>`, which must be
# [A-Za-z0-9_-]+. A dotted name like `foo.bar.yml` (splitext strips only `.yml`) would yield the key
# `index_pipeline_foo.bar` - invalid, and it fails at DEPLOY, not generation. Enforce it here so a
# bad name fails loudly at generation instead.
_VALID_STEM = re.compile(r"^[A-Za-z0-9_-]+$")

# First line of every generated file. Doubles as the marker that identifies OUR files in resources/
# (so hand-authored resources like deploy_views.job.yml are never touched or flagged as orphans).
_GENERATED_MARKER = "# GENERATED by scripts/gen_jobs.py"
_GENERATED_HEADER = (
    _GENERATED_MARKER + " from _pipelines/pipeline_configs/{config}. DO NOT EDIT BY HAND.\n"
    "# To change this job: edit the config or the generator template, then rerun the generator.\n"
)


def _config_name(path: str) -> str:
    """The stem used for the job key and generated filename (extension-agnostic)."""
    return os.path.splitext(os.path.basename(path))[0]


def load_job_cluster_spec(key: str) -> dict:
    """Load and lightly validate the reusable new_cluster spec named `key`. Fail closed.

    Looks for _pipelines/job_cluster_configs/<key>.yml (or .yaml). The file's contents are a Databricks
    `new_cluster` spec, passed through VERBATIM into the generated job's job_clusters block; the bundle
    (and the Jobs API at deploy) validate the spec's own fields, so we only enforce here that it exists
    and parses to a NON-EMPTY MAPPING. A missing file or a non-mapping/empty body raises, so a bad
    compute.job_cluster_config reference aborts generation rather than emitting a job with no/blank
    cluster. `key` is already charset-restricted by config validation, so it maps to one file safely.
    """
    path = next(
        (p for ext in (".yml", ".yaml") if os.path.exists(p := os.path.join(_JOB_CLUSTER_CONFIG_DIR, f"{key}{ext}"))),
        None,
    )
    if path is None:
        raise ValueError(
            f"compute.job_cluster_config '{key}' not found: expected "
            f"_pipelines/job_cluster_configs/{key}.yml (or .yaml)"
        )
    with open(path) as fh:
        spec = yaml.safe_load(fh)
    if not isinstance(spec, dict) or not spec:
        raise ValueError(
            f"_pipelines/job_cluster_configs/{key}: must be a non-empty mapping (a Databricks "
            f"new_cluster spec), got {type(spec).__name__}"
        )
    return spec


def _read_bundle_doc(path: str = _DATABRICKS_YML) -> dict:
    """Parse databricks.yml once. main() reads several things from it, so it parses once here and passes
    the parsed doc to the loaders below (their `doc=` argument), opening the file a single time per run.
    The loaders keep a path default so each is still independently callable (and unit-testable) on its own.
    """
    with open(path) as fh:
        return yaml.safe_load(fh) or {}


def _load_complex_configs(fields: frozenset, path: str = _DATABRICKS_YML, doc: dict | None = None) -> set:
    """Names of databricks.yml `type: complex` variables whose default mapping's keys are EXACTLY `fields`.

    The shared scan behind load_es_host_configs and load_cluster_configs (they differ only in the field
    set), so the "complex var with an exact key set" logic lives in one place. A complex variable with a
    different key set, and any plain (non-complex) variable, are ignored - so a config name can only ever
    resolve to a variable of the intended shape, never an unrelated one.
    """
    variables = (doc if doc is not None else _read_bundle_doc(path)).get("variables") or {}
    return {
        name for name, spec in variables.items()
        if isinstance(spec, dict) and spec.get("type") == "complex"
        and isinstance(spec.get("default"), dict) and set(spec["default"]) == fields
    }


def load_es_host_configs(path: str = _DATABRICKS_YML, doc: dict | None = None) -> set:
    """The set of declared Elasticsearch host-config names, read from databricks.yml. Fail closed.

    A host config is a bundle variable with `type: complex` whose default mapping's keys are exactly
    _ES_HOST_CONFIG_FIELDS (es_host_url + secret_scope_name + secret_key_name). This is the SINGLE
    SOURCE OF TRUTH for which host configs exist: a pipeline's `es_host_config` must name one of these
    (enforced by require_es_host_config), and the generated job references ${var.<name>.<field>}, which
    the bundle resolves per target at deploy. A complex variable whose default has a DIFFERENT key set is
    not a host config and is ignored, so unrelated complex variables never collide with this scan.
    """
    return _load_complex_configs(_ES_HOST_CONFIG_FIELDS, path, doc)


def load_default_es_host_config(path: str = _DATABRICKS_YML, doc: dict | None = None):
    """The bundle's default host-config name, from databricks.yml `variables.default_es_host_config.default`
    (or None if not declared). A pipeline that OMITS es_host_config falls back to this (see main).

    Read at GENERATION time from the variable's static `default:`; per-target and --var overrides are
    deploy-time and deliberately not visible here (the default host-config NAME is a repo-level choice,
    while its per-environment VALUES live on the host config itself). The value is returned as-is; whether
    it names a real declared host config is enforced by require_es_host_config once a pipeline resolves to it.
    """
    if doc is None:
        doc = _read_bundle_doc(path)
    spec = (doc.get("variables") or {}).get("default_es_host_config")
    if not isinstance(spec, dict):
        return None
    default = spec.get("default")
    if not (isinstance(default, str) and default):
        return None
    # A pipeline that omits es_host_config falls back to this name, which the generator emits as
    # ${var.<name>.es_host_url}. Hold it to the SAME identifier rule as a pipeline's own es_host_config
    # (config.py _require_identifier), so a malformed default (e.g. a hyphen) fails here with a clear
    # message rather than a confusing "not declared" error or a broken ${var.bad-name.*} ref downstream.
    _require_identifier(default, "default_es_host_config (databricks.yml)")
    return default


def require_es_host_config(name: str, declared: set) -> None:
    """Fail closed if a pipeline's es_host_config `name` is not declared in databricks.yml.

    Mirrors load_job_cluster_spec's role for job_cluster_config: a reference to a host config that was
    never declared (a typo, or one removed from databricks.yml) aborts generation with a clear message,
    rather than emitting a job whose ${var.<name>.*} references would fail only later, at deploy.
    """
    if name not in declared:
        raise ValueError(
            f"es_host_config '{name}' is not declared in databricks.yml "
            f"(declared host configs: {', '.join(sorted(declared)) or '<none>'}); add it as a "
            f"`type: complex` variable with es_host_url/secret_scope_name/secret_key_name fields, "
            f"or fix the pipeline's es_host_config"
        )


def load_cluster_configs(path: str = _DATABRICKS_YML, doc: dict | None = None) -> set:
    """The set of declared cluster-config names, read from databricks.yml. Fail closed.

    A cluster config is a bundle variable with `type: complex` whose default mapping's keys are exactly
    _CLUSTER_CONFIG_FIELDS ({cluster_id}). This is the SINGLE SOURCE OF TRUTH for which cluster configs
    exist: an existing_cluster pipeline's `cluster_config` must name one of these (enforced by
    require_cluster_config), and the generated job references ${var.<name>.cluster_id}, resolved per target
    at deploy. Exactly like load_es_host_configs: a complex variable with a DIFFERENT key set (e.g. a host
    config) or a plain string variable (wheel_path, environment, ...) is NOT a cluster config and is
    ignored, so cluster_config can only ever name a real, purpose-shaped cluster-id variable.
    """
    return _load_complex_configs(_CLUSTER_CONFIG_FIELDS, path, doc)


def require_cluster_config(name: str, declared: set) -> None:
    """Fail closed if an existing_cluster pipeline's cluster_config `name` is not a declared cluster config
    in databricks.yml. Mirrors require_es_host_config: a reference that is a typo, left commented out, or
    points at a variable that is NOT a cluster-id config (a host config, wheel_path, ...) aborts generation
    with a clear message, rather than emitting a job whose ${var.<name>.cluster_id} would fail at deploy.
    """
    if name not in declared:
        raise ValueError(
            f"cluster_config '{name}' is not declared as a cluster config in databricks.yml "
            f"(declared cluster configs: {', '.join(sorted(declared)) or '<none>'}); add it as a "
            f"`type: complex` variable with a single cluster_id field (with per-target values), "
            f"or fix the pipeline's cluster_config"
        )


def render_job_yaml(config_filename: str, name: str, cfg: dict, job_cluster_spec: dict | None = None) -> str:
    """Render the resources/<name>.job.yml content for one index config.

    Built as a dict and serialized with yaml.safe_dump, NOT hand-interpolated: the YAML writer escapes
    any special characters in the values, so a name/table/key containing a quote, colon, brace, etc.
    can never produce malformed YAML. Deterministic (sort_keys=False preserves this insertion order),
    so --check can compare byte-for-byte. On-demand, CAN_MANAGE_RUN to `users` - consistent with the
    other jobs in this bundle.

    max_concurrent_runs is hard-fixed to 1 for every job (not a config knob): a second concurrent run
    of the same index would double-write to the same ES index, and for a streaming job would contend
    on the one checkpoint. Serial-only is the invariant, so it is baked in here, not exposed.

    Compute (cfg["compute"], per-index) decides WHERE the notebook task runs:
    - serverless (default): no cluster block => serverless notebook task.
    - existing_cluster: the task gets existing_cluster_id: ${var.<name>.cluster_id}, from the config's
      cluster_config (a `type: complex` bundle variable), which the bundle resolves per target at deploy.
    - job_cluster: the job gets a job_clusters entry (job_cluster_key + the inlined new_cluster spec,
      passed in as `job_cluster_spec`) and the task references it by job_cluster_key. `job_cluster_spec`
      is REQUIRED for a job_cluster compute (the caller loads it via load_job_cluster_spec) and unused
      otherwise; a job_cluster compute without it is a caller bug and fails closed here. The inlined
      new_cluster also gets a policy_id bound to the cluster_policy_id bundle variable (plus
      apply_policy_default_values: true so the policy's own defaults fill omitted attrs), so the target's
      single cluster policy is applied to every job cluster at deploy (see the job_cluster block below).
      Any custom_tags (and every other field) in the spec file pass through VERBATIM - the spec is
      inlined as-is, so hardcoded tags like `project: elastic` land on the cluster with no special handling.

    Schedule (cfg["schedule"], per-index) decides WHEN the job runs: None => on-demand (no schedule
    block); otherwise a job `schedule` with the config's quartz_cron_expression, timezone_id UTC, and
    pause_status bound to the schedule_pause_status bundle variable (so a target can pause its schedules).
    """
    compute = cfg["compute"]
    ctype = compute["type"]

    # For existing_cluster, the cluster id is a ${var.<name>.cluster_id} reference into the config's
    # cluster_config complex variable, which the bundle resolves to the per-target cluster id at deploy.
    existing_cluster_ref = None
    if ctype == "existing_cluster":
        existing_cluster_ref = f"${{var.{compute['cluster_config']}.cluster_id}}"

    if ctype == "serverless":
        compute_desc = "No cluster block => serverless notebook task."
    elif ctype == "existing_cluster":
        compute_desc = f"Runs on existing cluster {existing_cluster_ref}."
    else:  # job_cluster
        compute_desc = (
            f"Runs on job cluster '{compute['job_cluster_config']}' "
            "(new_cluster spec from _pipelines/job_cluster_configs/)."
        )

    # Build the task, inserting the cluster reference (if any) between task_key and notebook_task.
    task: dict = {"task_key": f"index_pipeline_{name}"}
    if ctype == "existing_cluster":
        task["existing_cluster_id"] = existing_cluster_ref
    elif ctype == "job_cluster":
        task["job_cluster_key"] = compute["job_cluster_config"]
    # The ES connection is a per-pipeline choice: cfg["es_host_config"] names a `type: complex` bundle
    # variable (declared in databricks.yml, with per-target values) whose fields carry the endpoint and
    # the secret scope/key. Emit references to that variable's fields; the bundle resolves them per
    # target at deploy. main() has already resolved any omitted es_host_config to the bundle default and
    # validated the name is declared (require_es_host_config), so by here it is safe to build the refs.
    # Fail closed if it is still unset (a caller bug: the default was not resolved), like the job_cluster
    # spec guard below - never emit a ${var.None.*} ref. Built with format purely for clarity.
    hc = cfg["es_host_config"]
    if not hc:
        raise ValueError(
            f"es_host_config for '{name}' is unset; the caller must resolve the default "
            f"(default_es_host_config) before rendering"
        )
    task["notebook_task"] = {
        "notebook_path": "../notebooks/run_index_pipeline.py",
        # The notebook loads its own config at runtime (the generator can't know the deploy-time
        # values), so it just needs the config name plus the deploy-time bundle-variable refs
        # (environment, wheel_path, this pipeline's ES host-config fields, and the checkpoint base).
        "base_parameters": job_base_parameters(
            name,
            "${var.environment}",
            "${var.wheel_path}",
            f"${{var.{hc}.es_host_url}}",
            f"${{var.{hc}.secret_scope_name}}",
            f"${{var.{hc}.secret_key_name}}",
            "${var.checkpoint_base_path}",
        ),
    }

    # Assemble the job dict incrementally so key ORDER is deterministic (name, description,
    # max_concurrent_runs, parameters, [job_clusters], tasks, permissions) regardless of compute type,
    # keeping --check's byte-for-byte compare stable.
    job_def: dict = {
        # Display name uses the config NAME (the same stem as the resource key index_pipeline_<name>
        # and the config filename), not es_index_name, so a job is identified by its pipeline config -
        # the unit you edit and deploy - and lines up with its resource key. The target ES index is
        # still named in the description below.
        "name": f"[${{bundle.target}}] databricks-elasticsearch-pipelines: {name}",
        "description": (
            f"Export pipeline for the {cfg['es_index_name']} Elasticsearch index. Runs the shared "
            f"notebook notebooks/run_index_pipeline.py with this index's config. {compute_desc}"
        ),
        # Never run two copies of the same index pipeline at once (double-write / checkpoint
        # contention). Fixed at 1 for all jobs, deliberately not parameterized.
        "max_concurrent_runs": 1,
        # Run-time-overridable job parameters (pipeline_mode, filter_condition, and the EsWriteConfig
        # tuning knobs): defaults come from the config, overridable per run with `--params <name>=<value>`.
        "parameters": job_parameters(cfg),
    }
    # Optional schedule: when the config sets one, the job runs on that Quartz cron; otherwise it stays
    # on-demand (no schedule block). Timezone is always UTC (not a config knob).
    #
    # pause_status is a bundle variable (schedule_pause_status, default PAUSED = fail-safe) so a target
    # decides whether its schedules fire without editing any config: dev and stg inherit the PAUSED
    # default (deploy but never fire) and only prd binds UNPAUSED. Default PAUSED rather than relying on
    # `mode: development` to pause dev, because an explicit pause_status is honored as-is (development
    # mode does not override it), so the safe value must be the default.
    if cfg["schedule"] is not None:
        job_def["schedule"] = {
            "quartz_cron_expression": cfg["schedule"]["quartz_cron_expression"],
            "timezone_id": "UTC",
            "pause_status": "${var.schedule_pause_status}",
        }
    if ctype == "job_cluster":
        if job_cluster_spec is None:
            raise ValueError(
                f"job_cluster compute for '{name}' requires a loaded new_cluster spec "
                f"(job_cluster_config '{compute['job_cluster_config']}'); none was provided"
            )
        # Apply the target's single cluster policy to every job cluster: inject policy_id bound to the
        # cluster_policy_id bundle variable (one policy per environment, set at deploy). The variable is
        # authoritative - it overrides any policy_id in the spec file - because the policy is an
        # ENVIRONMENT property, not part of the reusable, environment-agnostic new_cluster spec. Also
        # inject apply_policy_default_values: true so the policy's fixed AND default values fill any
        # attribute the spec omits (e.g. aws_attributes the policy fixes/defaults) - this lets a spec
        # stay minimal and conform to ANY target's policy without hand-copying that policy's values here
        # (which would drift per environment). apply_policy_default_values only fills OMITTED fields, so a
        # value the spec sets explicitly still wins. Built as a COPY (new dict) so the caller's loaded
        # spec is not mutated; custom_tags and all other spec fields pass through verbatim. NOTE:
        # cluster_policy_id defaults to empty; a target that uses a job cluster MUST bind it (an empty
        # policy_id resolves to a literal "" that the Jobs API rejects at deploy - verified), so this
        # feature requires the deployer to set the variable per target.
        new_cluster = {
            **job_cluster_spec,
            "policy_id": "${var.cluster_policy_id}",
            "apply_policy_default_values": True,
        }
        job_def["job_clusters"] = [
            {"job_cluster_key": compute["job_cluster_config"], "new_cluster": new_cluster}
        ]
    job_def["tasks"] = [task]
    job_def["permissions"] = [{"level": "CAN_MANAGE_RUN", "group_name": "users"}]

    job = {"resources": {"jobs": {f"index_pipeline_{name}": job_def}}}
    body = yaml.safe_dump(job, sort_keys=False, default_flow_style=False, width=100, allow_unicode=True)
    return _GENERATED_HEADER.format(config=config_filename) + body


def generated_path(name: str) -> str:
    return os.path.join(_RESOURCES_DIR, f"{name}.job.yml")


def is_generated(path: str) -> bool:
    """True if the file at `path` carries our generated-marker header (so we own it)."""
    if not os.path.exists(path):
        return False
    with open(path) as fh:
        return fh.readline().startswith(_GENERATED_MARKER)


def existing_generated_files() -> list[str]:
    """Every resources/*.job.yml this generator authored, identified by the marker header.

    Used to spot orphans: a generated file whose config was deleted or renamed. Hand-authored
    resources (no marker) are excluded, so they are never removed or flagged.
    """
    return [
        path
        for path in sorted(glob.glob(os.path.join(_RESOURCES_DIR, "*.job.yml")))
        if is_generated(path)
    ]


def discover_configs() -> list[str]:
    """All config paths across the supported extensions, sorted, with collisions rejected."""
    paths: list[str] = []
    for pattern in _CONFIG_GLOBS:
        paths.extend(glob.glob(os.path.join(_CONFIG_DIR, pattern)))
    paths = sorted(paths)

    seen: dict[str, str] = {}
    for path in paths:
        name = _config_name(path)
        if not _VALID_STEM.match(name):
            raise ValueError(
                f"{os.path.basename(path)}: config name '{name}' is not a valid resource key; "
                f"use only letters, digits, '_' and '-' (no dots or other characters)"
            )
        if name in seen:
            raise ValueError(
                f"config name collision: {os.path.basename(seen[name])} and "
                f"{os.path.basename(path)} both map to '{name}'"
            )
        seen[name] = path
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files are up to date")
    args = parser.parse_args(argv)

    config_paths = discover_configs()
    orphans = [
        p for p in existing_generated_files() if p not in {generated_path(_config_name(c)) for c in config_paths}
    ]

    # An empty config dir is only an error if there is also no orphan cleanup to do - otherwise we
    # still need to run so a deleted last config's stale generated job gets removed/flagged. (Orphan
    # handling below runs regardless of whether any configs remain.)
    if not config_paths and not orphans:
        print(f"no index configs found in {_CONFIG_DIR}", file=sys.stderr)
        return 1

    # Validate and render EVERYTHING before touching disk, so generation is all-or-nothing: an invalid
    # config aborts here with nothing written, never leaving resources/ half-regenerated. Also refuse
    # up front to write over a hand-authored resource - the symmetric guard to orphan deletion: a
    # config named e.g. `deploy_views` targets the existing resources/deploy_views.job.yml (no marker).
    # The declared ES host configs (single source of truth: databricks.yml). Loaded once, up front, so
    # every pipeline's es_host_config is validated against the same set (and a bundle with none declared
    # fails each referencing pipeline with a clear message). default_es_host_config is the fallback used
    # when a pipeline omits es_host_config (may be None if the bundle declares no default).
    # Parse databricks.yml once, then extract each set from the same parsed doc (single read per run).
    bundle_doc = _read_bundle_doc()
    es_host_configs = load_es_host_configs(doc=bundle_doc)
    default_es_host_config = load_default_es_host_config(doc=bundle_doc)
    # The declared cluster configs (databricks.yml complex vars with a cluster_id field), for validating
    # an existing_cluster pipeline's cluster_config reference.
    cluster_configs = load_cluster_configs(doc=bundle_doc)

    rendered: dict[str, str] = {}
    collisions = []
    for path in config_paths:
        name = _config_name(path)
        out_path = generated_path(name)
        if os.path.exists(out_path) and not is_generated(out_path):
            collisions.append(name)
            continue
        cfg = load_config(path)  # raises ValueError on any invalid config (fail closed)
        # Resolve the host config: the pipeline's own es_host_config, or the bundle default when it omits
        # one. If neither is set there is no ES host to write to, so fail closed here (nothing written).
        hc = cfg["es_host_config"] or default_es_host_config
        if not hc:
            raise ValueError(
                f"pipeline '{name}' omits es_host_config and no default_es_host_config is declared in "
                f"databricks.yml; set es_host_config in the pipeline, or declare a default_es_host_config"
            )
        # The resolved name must name a host config declared in databricks.yml; fail closed here rather
        # than emit a job whose ${var.<name>.*} refs would break at deploy. Store it back so
        # render_job_yaml emits the right refs whether it came from the pipeline or the default.
        cfg["es_host_config"] = hc
        require_es_host_config(hc, es_host_configs)
        # For a job_cluster compute, resolve its reusable new_cluster spec now (during the pre-write
        # render pass), so a missing/invalid job_cluster_config aborts here with nothing written -
        # same all-or-nothing guarantee as an invalid config.
        job_cluster_spec = None
        if cfg["compute"]["type"] == "job_cluster":
            job_cluster_spec = load_job_cluster_spec(cfg["compute"]["job_cluster_config"])
        # An existing_cluster pipeline names a cluster_config; it must reference a declared cluster config
        # (a complex var with a cluster_id field). Fail closed here rather than emit a job whose
        # ${var.<name>.cluster_id} would break at deploy. Keyed on compute type, like the job_cluster guard.
        if cfg["compute"]["type"] == "existing_cluster":
            require_cluster_config(cfg["compute"]["cluster_config"], cluster_configs)
        rendered[name] = render_job_yaml(os.path.basename(path), name, cfg, job_cluster_spec)
    if collisions:
        for name in collisions:
            print(
                f"refusing to overwrite hand-authored {os.path.relpath(generated_path(name), _REPO_ROOT)} "
                f"(no generated marker); rename the config '{name}'",
                file=sys.stderr,
            )
        return 1

    if args.check:
        stale = []
        for name, content in rendered.items():
            out_path = generated_path(name)
            existing = None
            if os.path.exists(out_path):
                with open(out_path) as fh:
                    existing = fh.read()
            if existing != content:
                stale.append(name)

        problem = False
        if stale:
            print("stale/missing generated job file(s) for: " + ", ".join(sorted(stale)), file=sys.stderr)
            problem = True
        if orphans:
            print(
                "orphaned generated job file(s) with no matching config: "
                + ", ".join(os.path.relpath(p, _REPO_ROOT) for p in orphans),
                file=sys.stderr,
            )
            problem = True
        if problem:
            print("run: python scripts/gen_jobs.py", file=sys.stderr)
            return 1
        print(f"all {len(rendered)} generated job file(s) up to date; no orphans")
        return 0

    # Write pass: everything already validated and rendered, so this cannot abort partway on a bad config.
    for name, content in rendered.items():
        out_path = generated_path(name)
        with open(out_path, "w") as fh:
            fh.write(content)
        print(f"wrote {os.path.relpath(out_path, _REPO_ROOT)}")
    for path in orphans:
        os.remove(path)
        print(f"removed orphaned {os.path.relpath(path, _REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
