#!/usr/bin/env python3
"""Generate one per-index job resource from each pipeline_definitions/<name>.yml config.

Adding an Elasticsearch index to the framework is: add pipeline_definitions/<name>.yml (and its
views/<view_name>.sql), then rerun this generator. It writes resources/<name>.job.yml, one per
config, all pointing at the shared notebook notebooks/run_index_pipeline.py.

Usage:
  python scripts/gen_jobs.py            # (re)generate resources/<name>.job.yml files
  python scripts/gen_jobs.py --check    # exit non-zero if any generated file is missing/stale/orphaned

--check is the drift guard: run it in CI (or before deploy) so a config edit that was not
regenerated -- or a generated job left behind by a deleted/renamed config -- fails loudly instead of
deploying a stale job set.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys

import yaml

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Import the shared config schema from the repo root, so validation is not re-implemented here.
sys.path.insert(0, _REPO_ROOT)
from pipeline_lib.config import PipelineConfigError, job_base_parameters, load_config  # noqa: E402

_CONFIG_DIR = os.path.join(_REPO_ROOT, "pipeline_definitions")
_RESOURCES_DIR = os.path.join(_REPO_ROOT, "resources")

# Config files may use either extension; both are treated identically.
_CONFIG_GLOBS = ("*.yml", "*.yaml")

# A config's stem becomes the Databricks bundle resource key `index_pipeline_<stem>`, which must be
# [A-Za-z0-9_-]+. A dotted name like `foo.bar.yml` (splitext strips only `.yml`) would yield the key
# `index_pipeline_foo.bar` -- invalid, and it fails at DEPLOY, not generation. Enforce it here so a
# bad name fails loudly at generation instead.
_VALID_STEM = re.compile(r"^[A-Za-z0-9_-]+$")

# First line of every generated file. Doubles as the marker that identifies OUR files in resources/
# (so hand-authored resources like deploy_views.job.yml are never touched or flagged as orphans).
_GENERATED_MARKER = "# GENERATED by scripts/gen_jobs.py"
_GENERATED_HEADER = (
    _GENERATED_MARKER + " from pipeline_definitions/{config}. DO NOT EDIT BY HAND.\n"
    "# To change this job: edit the config or the generator template, then rerun the generator.\n"
)


def _config_name(path: str) -> str:
    """The stem used for the job key and generated filename (extension-agnostic)."""
    return os.path.splitext(os.path.basename(path))[0]


def render_job_yaml(config_filename: str, name: str, cfg: dict) -> str:
    """Render the resources/<name>.job.yml content for one index config.

    Built as a dict and serialized with yaml.safe_dump, NOT hand-interpolated: the YAML writer escapes
    any special characters in the values, so a name/table/key containing a quote, colon, brace, etc.
    can never produce malformed YAML. Deterministic (sort_keys=False preserves this insertion order),
    so --check can compare byte-for-byte. Serverless notebook task (no cluster block), on-demand,
    CAN_MANAGE_RUN to `users` -- consistent with the other jobs in this bundle.
    """
    job = {
        "resources": {
            "jobs": {
                f"index_pipeline_{name}": {
                    "name": f"[${{bundle.target}}] databricks-elasticsearch-pipelines: {cfg['es_index_name']}",
                    "description": (
                        f"Export pipeline for the {cfg['es_index_name']} Elasticsearch index. Runs "
                        "the shared notebook notebooks/run_index_pipeline.py with this index's config. No "
                        "cluster block => serverless notebook task."
                    ),
                    "tasks": [
                        {
                            "task_key": f"index_pipeline_{name}",
                            "notebook_task": {
                                "notebook_path": "../notebooks/run_index_pipeline.py",
                                # The notebook loads its own config at runtime (the generator can't
                                # know the deploy-time environment or wheel path), so it just needs the
                                # config name plus the environment and wheel_path bundle-variable refs.
                                "base_parameters": job_base_parameters(
                                    name, "${var.environment}", "${var.wheel_path}"
                                ),
                            },
                        }
                    ],
                    "permissions": [{"level": "CAN_MANAGE_RUN", "group_name": "users"}],
                }
            }
        }
    }
    body = yaml.safe_dump(job, sort_keys=False, default_flow_style=False, width=100, allow_unicode=True)
    return _GENERATED_HEADER.format(config=config_filename) + body


def generated_path(name: str) -> str:
    return os.path.join(_RESOURCES_DIR, f"{name}.job.yml")


def is_generated(path: str) -> bool:
    """True if the file at `path` carries our generated-marker header (so we own it)."""
    if not os.path.exists(path):
        return False
    with open(path) as fh:
        return fh.readline().startswith(_GENERATED_MARKER)


def existing_generated_files() -> list[str]:
    """Every resources/*.job.yml this generator authored, identified by the marker header.

    Used to spot orphans: a generated file whose config was deleted or renamed. Hand-authored
    resources (no marker) are excluded, so they are never removed or flagged.
    """
    return [
        path
        for path in sorted(glob.glob(os.path.join(_RESOURCES_DIR, "*.job.yml")))
        if is_generated(path)
    ]


def discover_configs() -> list[str]:
    """All config paths across the supported extensions, sorted, with collisions rejected."""
    paths: list[str] = []
    for pattern in _CONFIG_GLOBS:
        paths.extend(glob.glob(os.path.join(_CONFIG_DIR, pattern)))
    paths = sorted(paths)

    seen: dict[str, str] = {}
    for path in paths:
        name = _config_name(path)
        if not _VALID_STEM.match(name):
            raise ValueError(
                f"{os.path.basename(path)}: config name '{name}' is not a valid resource key; "
                f"use only letters, digits, '_' and '-' (no dots or other characters)"
            )
        if name in seen:
            raise ValueError(
                f"config name collision: {os.path.basename(seen[name])} and "
                f"{os.path.basename(path)} both map to '{name}'"
            )
        seen[name] = path
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files are up to date")
    args = parser.parse_args(argv)

    config_paths = discover_configs()
    orphans = [
        p for p in existing_generated_files() if p not in {generated_path(_config_name(c)) for c in config_paths}
    ]

    # An empty config dir is only an error if there is also no orphan cleanup to do -- otherwise we
    # still need to run so a deleted last config's stale generated job gets removed/flagged. (Orphan
    # handling below runs regardless of whether any configs remain.)
    if not config_paths and not orphans:
        print(f"no index configs found in {_CONFIG_DIR}", file=sys.stderr)
        return 1

    # Validate and render EVERYTHING before touching disk, so generation is all-or-nothing: an invalid
    # config aborts here with nothing written, never leaving resources/ half-regenerated. Also refuse
    # up front to write over a hand-authored resource -- the symmetric guard to orphan deletion: a
    # config named e.g. `deploy_views` targets the existing resources/deploy_views.job.yml (no marker).
    rendered: dict[str, str] = {}
    collisions = []
    for path in config_paths:
        name = _config_name(path)
        out_path = generated_path(name)
        if os.path.exists(out_path) and not is_generated(out_path):
            collisions.append(name)
            continue
        cfg = load_config(path)  # raises ValueError on any invalid config (fail closed)
        rendered[name] = render_job_yaml(os.path.basename(path), name, cfg)
    if collisions:
        for name in collisions:
            print(
                f"refusing to overwrite hand-authored {os.path.relpath(generated_path(name), _REPO_ROOT)} "
                f"(no generated marker); rename the config '{name}'",
                file=sys.stderr,
            )
        return 1

    if args.check:
        stale = []
        for name, content in rendered.items():
            out_path = generated_path(name)
            existing = None
            if os.path.exists(out_path):
                with open(out_path) as fh:
                    existing = fh.read()
            if existing != content:
                stale.append(name)

        problem = False
        if stale:
            print("stale/missing generated job file(s) for: " + ", ".join(sorted(stale)), file=sys.stderr)
            problem = True
        if orphans:
            print(
                "orphaned generated job file(s) with no matching config: "
                + ", ".join(os.path.relpath(p, _REPO_ROOT) for p in orphans),
                file=sys.stderr,
            )
            problem = True
        if problem:
            print("run: python scripts/gen_jobs.py", file=sys.stderr)
            return 1
        print(f"all {len(rendered)} generated job file(s) up to date; no orphans")
        return 0

    # Write pass: everything already validated and rendered, so this cannot abort partway on a bad config.
    for name, content in rendered.items():
        out_path = generated_path(name)
        with open(out_path, "w") as fh:
            fh.write(content)
        print(f"wrote {os.path.relpath(out_path, _REPO_ROOT)}")
    for path in orphans:
        os.remove(path)
        print(f"removed orphaned {os.path.relpath(path, _REPO_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
