#!/usr/bin/env python3
"""Generate one per-index job resource from each index_pipelines/<name>.yml config.

Adding an Elasticsearch index to the framework is: add index_pipelines/<name>.yml (and its
views/<view_name>.sql), then rerun this generator. It writes resources/<name>.job.yml, one per
config, all pointing at the shared notebook src/run_index_pipeline.py.

Usage:
  python scripts/gen_jobs.py            # (re)generate resources/<name>.job.yml files
  python scripts/gen_jobs.py --check    # exit non-zero if any generated file is missing/stale/orphaned

--check is the drift guard: run it in CI (or before deploy) so a config edit that was not
regenerated -- or a generated job left behind by a deleted/renamed config -- fails loudly instead of
deploying a stale job set.
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys

import yaml

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_CONFIG_DIR = os.path.join(_REPO_ROOT, "index_pipelines")
_RESOURCES_DIR = os.path.join(_REPO_ROOT, "resources")

# Config files may use either extension; both are treated identically.
_CONFIG_GLOBS = ("*.yml", "*.yaml")

# A config's stem becomes the Databricks bundle resource key `index_pipeline_<stem>`, which must be
# [A-Za-z0-9_-]+. A dotted name like `foo.bar.yml` (splitext strips only `.yml`) would yield the key
# `index_pipeline_foo.bar` -- invalid, and it fails at DEPLOY, not generation. Enforce it here so a
# bad name fails loudly at generation instead.
_VALID_STEM = re.compile(r"^[A-Za-z0-9_-]+$")

# Required keys in every index config. Allow-list: an unknown key is rejected (a typo'd key would
# otherwise be silently ignored, e.g. `primary_keys:` leaving primary_key unset), and a missing or
# non-string/empty value is rejected. Both fail closed.
_REQUIRED_KEYS = ("es_index_name", "source_table", "view_name", "primary_key")

# First line of every generated file. Doubles as the marker that identifies OUR files in resources/
# (so hand-authored resources like deploy_views.job.yml are never touched or flagged as orphans).
_GENERATED_MARKER = "# GENERATED by scripts/gen_jobs.py"
_GENERATED_HEADER = (
    _GENERATED_MARKER + " from index_pipelines/{config}. DO NOT EDIT BY HAND.\n"
    "# To change this job: edit the config or the generator template, then rerun the generator.\n"
)


def _config_name(path: str) -> str:
    """The stem used for the job key and generated filename (extension-agnostic)."""
    return os.path.splitext(os.path.basename(path))[0]


def load_config(path: str) -> dict:
    """Load and validate one index config. Raises ValueError on any problem (fail closed).

    Returns the config with every required value stripped, so rendering is deterministic and cannot
    be fed leading/trailing whitespace.
    """
    with open(path) as fh:
        cfg = yaml.safe_load(fh)
    if not isinstance(cfg, dict):
        raise ValueError(f"{os.path.basename(path)}: expected a YAML mapping, got {type(cfg).__name__}")

    unknown = sorted(set(cfg) - set(_REQUIRED_KEYS))
    if unknown:
        raise ValueError(
            f"{os.path.basename(path)}: unknown key(s): {', '.join(unknown)}; "
            f"allowed: {', '.join(_REQUIRED_KEYS)}"
        )

    result: dict[str, str] = {}
    problems: list[str] = []
    for key in _REQUIRED_KEYS:
        if key not in cfg:
            problems.append(f"{key} (missing)")
            continue
        value = cfg[key]
        # Must be a non-empty string. A null value (`es_index_name:` with nothing after it) parses to
        # None, and a bare number/list to int/list; none are valid here. Rejecting them closes the
        # fail-open hole where str(None) == "None" would sail past an emptiness check and render the
        # literal "None" into the job. Numeric-looking names must be quoted in the YAML to be strings.
        if not isinstance(value, str) or not value.strip():
            problems.append(f"{key} (must be a non-empty string, got {type(value).__name__}: {value!r})")
            continue
        result[key] = value.strip()

    if problems:
        raise ValueError(f"{os.path.basename(path)}: invalid required key(s): " + "; ".join(problems))
    return result


def render_job_yaml(config_filename: str, name: str, cfg: dict) -> str:
    """Render the resources/<name>.job.yml content for one index config.

    Built as a dict and serialized with yaml.safe_dump, NOT hand-interpolated: the YAML writer escapes
    any special characters in the values, so a name/table/key containing a quote, colon, brace, etc.
    can never produce malformed YAML. Deterministic (sort_keys=False preserves this insertion order),
    so --check can compare byte-for-byte. Serverless notebook task (no cluster block), on-demand,
    CAN_MANAGE_RUN to `users` -- consistent with the other jobs in this bundle.
    """
    job = {
        "resources": {
            "jobs": {
                f"index_pipeline_{name}": {
                    "name": f"[${{bundle.target}}] databricks-elasticsearch-pipelines: {cfg['es_index_name']}",
                    "description": (
                        f"Export pipeline for the {cfg['es_index_name']} Elasticsearch index. Runs "
                        "the shared notebook src/run_index_pipeline.py with this index's config. No "
                        "cluster block => serverless notebook task."
                    ),
                    "tasks": [
                        {
                            "task_key": f"index_pipeline_{name}",
                            "notebook_task": {
                                "notebook_path": "../src/run_index_pipeline.py",
                                "base_parameters": {
                                    "es_index_name": cfg["es_index_name"],
                                    "source_table": cfg["source_table"],
                                    "view_name": cfg["view_name"],
                                    "primary_key": cfg["primary_key"],
                                },
                            },
                        }
                    ],
                    "permissions": [{"level": "CAN_MANAGE_RUN", "group_name": "users"}],
                }
            }
        }
    }
    body = yaml.safe_dump(job, sort_keys=False, default_flow_style=False, width=100, allow_unicode=True)
    return _GENERATED_HEADER.format(config=config_filename) + body


def generated_path(name: str) -> str:
    return os.path.join(_RESOURCES_DIR, f"{name}.job.yml")


def existing_generated_files() -> list[str]:
    """Every resources/*.job.yml this generator authored, identified by the marker header.

    Used to spot orphans: a generated file whose config was deleted or renamed. Hand-authored
    resources (no marker) are excluded, so they are never removed or flagged.
    """
    out = []
    for path in sorted(glob.glob(os.path.join(_RESOURCES_DIR, "*.job.yml"))):
        with open(path) as fh:
            if fh.readline().startswith(_GENERATED_MARKER):
                out.append(path)
    return out


def discover_configs() -> list[str]:
    """All config paths across the supported extensions, sorted, with collisions rejected."""
    paths: list[str] = []
    for pattern in _CONFIG_GLOBS:
        paths.extend(glob.glob(os.path.join(_CONFIG_DIR, pattern)))
    paths = sorted(paths)

    seen: dict[str, str] = {}
    for path in paths:
        name = _config_name(path)
        if not _VALID_STEM.match(name):
            raise ValueError(
                f"{os.path.basename(path)}: config name '{name}' is not a valid resource key; "
                f"use only letters, digits, '_' and '-' (no dots or other characters)"
            )
        if name in seen:
            raise ValueError(
                f"config name collision: {os.path.basename(seen[name])} and "
                f"{os.path.basename(path)} both map to '{name}'"
            )
        seen[name] = path
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated files are up to date")
    args = parser.parse_args(argv)

    config_paths = discover_configs()
    if not config_paths:
        print(f"no index configs found in {_CONFIG_DIR}", file=sys.stderr)
        return 1

    expected = {generated_path(_config_name(p)) for p in config_paths}
    orphans = [p for p in existing_generated_files() if p not in expected]

    stale = []
    for path in config_paths:
        name = _config_name(path)
        cfg = load_config(path)
        content = render_job_yaml(os.path.basename(path), name, cfg)
        out_path = generated_path(name)

        if args.check:
            existing = None
            if os.path.exists(out_path):
                with open(out_path) as fh:
                    existing = fh.read()
            if existing != content:
                stale.append(name)
        else:
            with open(out_path, "w") as fh:
                fh.write(content)
            print(f"wrote {os.path.relpath(out_path, _REPO_ROOT)}")

    if not args.check:
        for path in orphans:
            os.remove(path)
            print(f"removed orphaned {os.path.relpath(path, _REPO_ROOT)}")

    if args.check:
        problem = False
        if stale:
            print(
                "stale/missing generated job file(s) for: " + ", ".join(stale),
                file=sys.stderr,
            )
            problem = True
        if orphans:
            print(
                "orphaned generated job file(s) with no matching config: "
                + ", ".join(os.path.relpath(p, _REPO_ROOT) for p in orphans),
                file=sys.stderr,
            )
            problem = True
        if problem:
            print("run: python scripts/gen_jobs.py", file=sys.stderr)
            return 1
        print(f"all {len(config_paths)} generated job file(s) up to date; no orphans")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
